project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false

compiler:
    evm_version: null
    solc:
        version: 0.7.6
        optimizer:
            enabled: true
            runs: 200
        remappings: 
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.1-solc-0.7-2"
          - "@uniswap/v3-core=Uniswap/v3-core@1.0.0"
          - "@uniswap/lib=Uniswap/uniswap-lib@4.0.0-alpha"
          - "@uniswap/v2-core=Uniswap/v2-core@1.0.1"
          - "@uniswap/periphery=Uniswap/v3-periphery@1.0.0"
          - "base64-sol/base64.sol=Brechtpd/base64@1.1.0/base64.sol"
          #- "@uniswap=Uniswap/v3-core@1.0.0"
          #- "@uniswapp=Uniswap/v3-periphery@1.3.0"
    vyper:
        version: null

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs

reports:
    exclude_paths: null
    exclude_contracts: null
    only_include_project: true

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true

autofetch_sources: false
dependencies: 
 - openzeppelin/openzeppelin-contracts@3.4.1-solc-0.7-2
 - brechtpd/base64@1.1.0
 - uniswap/v3-core@1.0.0
 - uniswap/v2-core@1.0.0
 - uniswap/uniswap-lib@4.0.0-alpha
 - uniswap/v3-periphery@1.0.0
dev_deployment_artifacts: falsebro